artifact_location: file:///C:/Users/MD Arsheer/MLOPS Project/mlflow/217242364271399938
creation_time: 1784815831471
effective_trace_archival_retention: null
experiment_id: '217242364271399938'
last_update_time: 1784815831471
lifecycle_stage: active
name: Smart_Product_Recommendation_System
trace_location: null
workspace: default
